language: go

go:
  - 1.14
  - tip

env:
  - CGO_ENABLED=0

install:
  - go get github.com/golang/lint/golint

script:
  - diff <(echo -n) <(gofmt -s -d .)
  - go vet ./...
  - go test ./...
  - make test

after_script:
  - golint ./...
